name: Build Phalcon PECL package

on:
  workflow_call:
    inputs:
      extensions:
        description: 'PHP extensions which must be installed for current PHP version.'
        type: string
        required: true
    secrets:
      composer-token:
        required: false

jobs:
  stubs:
    name: Build Phalcon PECL package

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: ${{ inputs.extensions }}
          tools: pecl
        env:
          COMPOSER_TOKEN: ${{ secrets.composer-token }}

      - name: Setup APT Repositories
        run: |
          # We don't need this at all, and our
          # builds often fails because Microsoft
          # servers are unstable or even offline.
          sudo rm -f /etc/apt/sources.list.d/dotnetdev.list
          sudo rm -f /etc/apt/sources.list.d/azure*.list

      - name: Install System Dependencies
        run: |
          sudo apt-get update --quiet --yes 1>/dev/null
          sudo apt-get install --no-install-recommends -q -y re2c

      - name: Install Zephir
        run: .ci/install-zephir.sh

      - name: Generate C Code
        run: |
          $HOME/bin/zephir fullclean
          $HOME/bin/zephir generate
          (cd build && php gen-build.php)

      - name: Upload compile-errors.log
        uses: actions/upload-artifact@v2
        with:
          name: compile-errors
          path: compile-errors.log

      - name: Create Pecl Package (PHP 8)
        id: pecl_create
        run: |
          cp build/phalcon/config.w32 config.w32
          cp build/phalcon/phalcon.zep.c phalcon.zep.c
          cp build/phalcon/config.m4 config.m4
          cp build/phalcon/php_phalcon.h php_phalcon.h
          cp build/phalcon/phalcon.zep.h phalcon.zep.h
          pecl package
          phalcon_package="`ls | grep phalcon-*tgz`"
          mv $phalcon_package phalcon-pecl.tgz

      - name: Validate Pecl Package
        run: pecl package-validate phalcon-pecl.tgz

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: 'phalcon-pecl'
          path: phalcon-pecl.tgz
