name: Phalcon Stubs Generation with Zephir for current project

on:
  workflow_call:
    inputs:
      extensions:
        description: 'PHP extensions which must be installed for current PHP version.'
        type: string
        required: true

jobs:
  stubs:
    name: Check with Psalm / PHP ${{ matrix.php }}

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1', '8.2', '8.3' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl
          extensions: ${{ inputs.extensions }}

      - name: Install System Dependencies
        run: |
          sudo apt update --quiet --yes 1>/dev/null
          sudo apt install --no-install-recommends -q -y re2c

      - run: composer install --prefer-dist

      - name: Install Zephir
        run: .ci/install-zephir.sh

      - name: Validate stubs
        if: always()
        run: |
          $HOME/bin/zephir stubs
          vendor/bin/psalm ide/
