name: PHPCS inspection

on:
  workflow_call:
    inputs:
      standard:
        description: 'PHPCS standard'
        required: true
        type: string

jobs:
  phpcs:
    name: Check code style

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run PHP_CodeSniffer
        run: docker run --rm -v $(pwd):/data cytopia/phpcs --standard=${{ inputs.standard }}
